"""create tables

Revision ID: f89e53e44556
Revises: 
Create Date: 2020-08-13 00:24:03.883826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f89e53e44556'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friendships', sa.Column('accepter_id', sa.Integer(), nullable=True))
    op.add_column('friendships', sa.Column('requester_id', sa.Integer(), nullable=True))
    op.drop_constraint('friendships_requesters_id_fkey', 'friendships', type_='foreignkey')
    op.drop_constraint('friendships_accepters_id_fkey', 'friendships', type_='foreignkey')
    op.create_foreign_key(None, 'friendships', 'users', ['accepter_id'], ['id'])
    op.create_foreign_key(None, 'friendships', 'users', ['requester_id'], ['id'])
    op.drop_column('friendships', 'accepters_id')
    op.drop_column('friendships', 'requesters_id')
    op.add_column('likes', sa.Column('authors_id', sa.Integer(), nullable=True))
    op.drop_constraint('likes_author_id_fkey', 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'users', ['authors_id'], ['id'])
    op.drop_column('likes', 'author_id')
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.add_column('likes', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key('likes_author_id_fkey', 'likes', 'users', ['author_id'], ['id'])
    op.drop_column('likes', 'authors_id')
    op.add_column('friendships', sa.Column('requesters_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('friendships', sa.Column('accepters_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'friendships', type_='foreignkey')
    op.drop_constraint(None, 'friendships', type_='foreignkey')
    op.create_foreign_key('friendships_accepters_id_fkey', 'friendships', 'users', ['accepters_id'], ['id'])
    op.create_foreign_key('friendships_requesters_id_fkey', 'friendships', 'users', ['requesters_id'], ['id'])
    op.drop_column('friendships', 'requester_id')
    op.drop_column('friendships', 'accepter_id')
    # ### end Alembic commands ###
